spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scheduledwf
    username: scheduler
    password: scheduler
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080

scheduler:
  poll-interval-ms: 30000
  page-size: 50

conductor:
  url: http://localhost:8080
